name: Ping my server every 14 minutes (working hours)

on:
  schedule:
    - cron: '*/14 * * * *'
  workflow_dispatch:


jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping server
        run: timeout 60 curl -sSf https://zizi-app.onrender.com/api/ping/method
