name: Ping my server every 59 minutes (06:00–23:00 VN)

on:
  schedule:
    # VN 06:00–06:59 → UTC 23:00–23:59
    - cron: '*/59 23 * * *'
    # VN 07:00–22:59 → UTC 00:00–15:59
    - cron: '*/59 0-15 * * *'
    # VN 23:00 → UTC 16:00 (chạy 1 lần cuối cùng trong ngày)
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render server
        run: |
          echo "Pinging at $(date -u '+%Y-%m-%d %H:%M:%S') UTC"
          curl -sSf --max-time 30 "https://zizi-app-render.onrender.com/api/ping/method?from=github" \
            || echo "⚠️ Ping failed, server may be sleeping"
